# -*- coding: utf-8 -*-
"""Predictive Maintenance Oil Drilling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mv5uWpHMJfCkKmw-8zeMbyCUM5K55Fdh
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Data Collection
sensor_data = pd.read_csv('sensor_data.csv')

# Data Preprocessing
# Handle missing values
sensor_data.fillna(method='ffill', inplace=True)

# Normalize features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(sensor_data)

# Feature and Target Variables
X = scaled_data.drop(columns=['target']).values
y = scaled_data['target'].values

# Model Selection
model = Sequential([
    LSTM(64, input_shape=(X.shape[1], 1)),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

# Model Training
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape X_train and X_val for LSTM input
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_val = X_val.reshape((X_val.shape[0], X_val.shape[1], 1))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=32)

# Evaluation
loss, accuracy = model.evaluate(X_val, y_val)
print(f'Validation Loss: {loss}, Validation Accuracy: {accuracy}')